function getFillings(sandWitch){
return sandWitch.slice(1,sandWitch.length-1)
}
function getFillings(sandWitch){
    let a = []
    for(let i =1;i<sandWitch.length-1;i++){
        a.push(sandWitch[i])
    }
    return a
}
console.log(getFillings(["bread", "ham", "cheese", "ham", "bread"]), ["ham", "cheese", "ham"])
console.log(getFillings(["bread", "sausage", "tomato", "bread"]), ["sausage", "tomato"])
console.log(getFillings(["bread", "lettuce", "bacon", "tomato", "bread"]), ["lettuce", "bacon", "tomato"])
console.log(getFillings(["bread", "bacon", "lettuce", "tomato", "bread"]), ["bacon", "lettuce", "tomato"])
console.log(getFillings(["bread", "tomato", "tomato", "ham", "sausage", "bread"]), ["tomato", "tomato", "ham", "sausage"])
console.log(getFillings(["bread", "lettuce", "bread"]), ["lettuce"])
console.log(getFillings(["bread", "cheese", "bread"]), ["cheese"])
console.log(getFillings(["bread", "lettuce", "tomato", "ham", "bread"]), ["lettuce", "tomato", "ham"])
console.log(getFillings(["bread", "ham", "cheese", "lettuce", "ham", "bread"]), ["ham", "cheese", "lettuce", "ham"])
console.log(getFillings(["bread", "lettuce", "lettuce", "bread"]), ["lettuce", "lettuce"])
console.log(getFillings(["bread", "sausage", "ham", "bread"]), ["sausage", "ham"])
console.log(getFillings(["bread", "bacon", "bread"]), ["bacon"])
console.log(getFillings(["bread", "ham", "bread"]), ["ham"])
console.log(getFillings(["bread", "ham", "bread"]), ["ham"])
console.log(getFillings(["bread", "sausage", "ham", "lettuce", "bread"]), ["sausage", "ham", "lettuce"])
console.log(getFillings(["bread", "sausage", "bread"]), ["sausage"])
console.log(getFillings(["bread", "lettuce", "bread"]), ["lettuce"])
console.log(getFillings(["bread", "tomato", "lettuce", "cheese", "cheese", "bread"]), ["tomato", "lettuce", "cheese", "cheese"])
console.log(getFillings(["bread", "tomato", "sausage", "bacon", "tomato", "bread"]), ["tomato", "sausage", "bacon", "tomato"])
console.log(getFillings(["bread", "bacon", "ham", "lettuce", "tomato", "lettuce", "bread"]), ["bacon", "ham", "lettuce", "tomato", "lettuce"])
console.log(getFillings(["bread", "tomato", "lettuce", "cheese", "lettuce", "bread"]), ["tomato", "lettuce", "cheese", "lettuce"])
console.log(getFillings(["bread", "ham", "ham", "bacon", "ham", "cheese", "bread"]), ["ham", "ham", "bacon", "ham", "cheese"])
console.log(getFillings(["bread", "tomato", "bacon", "ham", "tomato", "bread"]), ["tomato", "bacon", "ham", "tomato"])
console.log(getFillings(["bread", "ham", "cheese", "lettuce", "bread"]), ["ham", "cheese", "lettuce"])
console.log(getFillings(["bread", "lettuce", "bread"]), ["lettuce"])
console.log(getFillings(["bread", "lettuce", "bacon", "bacon", "bread"]), ["lettuce", "bacon", "bacon"])
console.log(getFillings(["bread", "tomato", "cheese", "sausage", "bread"]), ["tomato", "cheese", "sausage"])
console.log(getFillings(["bread", "cheese", "ham", "bread"]), ["cheese", "ham"])
console.log(getFillings(["bread", "tomato", "bread"]), ["tomato"])
console.log(getFillings(["bread", "sausage", "bread"]), ["sausage"])
console.log(getFillings(["bread", "cheese", "bread"]), ["cheese"])
console.log(getFillings(["bread", "ham", "bacon", "sausage", "lettuce", "sausage", "bread"]), ["ham", "bacon", "sausage", "lettuce", "sausage"])
console.log(getFillings(["bread", "cheese", "lettuce", "lettuce", "bacon", "lettuce", "bread"]), ["cheese", "lettuce", "lettuce", "bacon", "lettuce"])
console.log(getFillings(["bread", "bacon", "sausage", "ham", "bacon", "bread"]), ["bacon", "sausage", "ham", "bacon"])
console.log(getFillings(["bread", "bacon", "tomato", "bread"]), ["bacon", "tomato"])
console.log(getFillings(["bread", "tomato", "bread"]), ["tomato"])
console.log(getFillings(["bread", "cheese", "cheese", "tomato", "bread"]), ["cheese", "cheese", "tomato"])
console.log(getFillings(["bread", "cheese", "tomato", "bread"]), ["cheese", "tomato"])
console.log(getFillings(["bread", "lettuce", "bread"]), ["lettuce"])
console.log(getFillings(["bread", "lettuce", "sausage", "bread"]), ["lettuce", "sausage"])
console.log(getFillings(["bread", "tomato", "tomato", "bread"]), ["tomato", "tomato"])
console.log(getFillings(["bread", "tomato", "lettuce", "cheese", "bacon", "bread"]), ["tomato", "lettuce", "cheese", "bacon"])
console.log(getFillings(["bread", "tomato", "lettuce", "bread"]), ["tomato", "lettuce"])
console.log(getFillings(["bread", "bacon", "bacon", "tomato", "lettuce", "bacon", "bread"]), ["bacon", "bacon", "tomato", "lettuce", "bacon"])
console.log(getFillings(["bread", "sausage", "sausage", "lettuce", "bread"]), ["sausage", "sausage", "lettuce"])
console.log(getFillings(["bread", "ham", "bacon", "ham", "ham", "bread"]), ["ham", "bacon", "ham", "ham"])
console.log(getFillings(["bread", "lettuce", "cheese", "lettuce", "bread"]), ["lettuce", "cheese", "lettuce"])
console.log(getFillings(["bread", "ham", "sausage", "cheese", "tomato", "bread"]), ["ham", "sausage", "cheese", "tomato"])
console.log(getFillings(["bread", "ham", "cheese", "bacon", "bread"]), ["ham", "cheese", "bacon"])
console.log(getFillings(["bread", "cheese", "tomato", "bread"]), ["cheese", "tomato"])
console.log(getFillings(["bread", "bacon", "lettuce", "ham", "tomato", "lettuce", "bread"]), ["bacon", "lettuce", "ham", "tomato", "lettuce"])
console.log(getFillings(["bread", "ham", "bacon", "bread"]), ["ham", "bacon"])
console.log(getFillings(["bread", "ham", "lettuce", "bread"]), ["ham", "lettuce"])